### ISSUE TITLE
axis expressions handle spaces?

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#1096]
Proposing to allow spaces when specifying axis expressions.  The spaces are just culled from the string.

Alternatively, we should throw an error/warning if spaces are included in the axis expression to help the user.

Not sure why we haven't done this, though, which probably means there is an issue implementing this.  Do we allow for variables/channels to have spaces in their names?  Should we?

**Comment by ksunden** [comment]
https://github.com/wright-group/WrightTools/blob/49501c45d80c531d3c257326b661060c46777dfb/WrightTools/data/_axis.py#L165

I think simply adding `+ "|\s"` to this line will fix the direct problem.

The actual evaluating of expressions is done using `numexpr` which can handle spaces just fine, the issue is that we split only on the operators when determining what variables exist which causes `"mono "` to be selected instead of `"mono"` which is then _not_ the name of a real variable, so it gets ignored.

**Comment by ksunden** [comment]
The other area I would have questions about behavior of expressions with spaces would be in the mangled name that is a valid identifier (the ones that look like `"w1__p__w2"`

I suspect that they would be replaced by `_` characters in that instance, which would perhaps get weird on trying to go back to the "human readable" form, but not sure we actually rely on that behavior as it is already not fully reversible anyway.
