### ISSUE TITLE
units

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#132]
I'm opening this issue because I want to be 100% open and honest about WrightTools and units. I know that units support is very important to WrightTools, and I want the package to be as good as possible. I also know that there is much more that WrightTools could do with units, and I'm open to the idea of overhauling units support moving forward.

That said, units get really hard really quickly. Our current humble home-brew strategy is simple and foolproof, which goes a long way. I'd prefer to not change the units API, if possible.

Should channels have units?

Should we fall back on a units library? Such as...
1) [pint](https://pint.readthedocs.io/en/0.8.1/)
2) [natu](https://kdavies4.github.io/natu/)
3) [magnitude](https://github.com/juanre/magnitude)
4) [scimath](https://github.com/enthought/scimath)
5) [quantities](https://pythonhosted.org/quantities/)
6) [units](https://bitbucket.org/adonohue/units/)
7) [SymPy](http://docs.sympy.org/latest/modules/physics/units/index.html)
8) [astropy](http://docs.astropy.org/en/stable/units/)
9) more?

**Comment by untzag** [comment]
[MetPy’s Choice of Unit Support - A Descent into Madness](https://www.youtube.com/watch?v=qCo9bkT9sow)

**Comment by ksunden** [comment]
I was looking into natu, and it seems on the surface to be logically organized, but then they made some quite strange decisions in what is considered a `base constant` versus `derived constant`

Most notably (that I found in quite short looking), the Faraday Constant is a `base constant` with units of `C/mol`, however, the Coulomb and Mole are derived constants

I cannot for the life of me determine why they decided to define `mol` as `96485.3365*Wb*cyc*S/k_F`
Which is to say Faradays constant times the weber times cycles times seimens divided by Faradays constant...  It may work out mathematically, but is way over-complicated

This is not the only example of circular definitions that they have due to their choice in what is considered "Base"

**Comment by ksunden** [comment]
scimath, (an enthought product by the looks of it), seems to take the logical approach of using SI base units as the internal representation. It does not, it seem immediately clear, have particularly good support for the kinds of unit manipulation that we do, in which we consider 'wavelength' and 'wavenumber/cm-1' to be energy units that can be converted easily. It would also require some finagling to get delay stages in place. In short, we would need to have our custom definitions as a layer between the underlying scimath and our programs, which does not seem to solve the problem of rolling our own units in the first place (Though may make our units more flexible in general, that would require careful implementation)

**Comment by ksunden** [comment]
SymPy looks like it may be a bit much for what we want, but is certainly worth looking into more deeply

**Comment by ksunden** [comment]
[unyt](https://github.com/yt-project/unyt)

**Comment by ksunden** [comment]
I think unyt can handle a lot of what we need with their idea of equivalencies (taken from astropy.units)

**Comment by ksunden** [comment]
unyt adds a sympy dependency, for the record (and sympy ads mpmath)
