### ISSUE TITLE
special instructions for contributing new `from` method

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#143]
Shall we provide a landing page with a dedicated checklist for contributing a new `from_x` method?

If so, where would that go?

**Comment by ksunden** [comment]
I think this is a good idea, but think perhaps we should let a couple people write some new ones first under some level of supervision (@neffmallon with Brunold group formats comes to mind) To see where questions arise


I think it would largely be a matter of reviewing over some of the particulars of the data object (with an eye towards importing rather than manipulating) and some guidelines for expected behaviors. Perhaps with copies of some of the existing `from_x` methods in line with commentary and links to the data files (in the repo) that they work with

**Comment by ksunden** [comment]
Add some discussion about recommended metadata conventions (see #352)
