### ISSUE TITLE
[h5] data kind and source

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#254]
data has optional `kind` and `source` attributes

`kind` identifies the data type
it has a one-to-one correspondence with the from function

`source` is the full path(s) to the file(s) that were used to create the object
the appropriate from function should be able to recreate the data object in its original form using `source`

we need to ensure that these guidelines are met for all of the from functions

**Comment by ksunden** [comment]
Relative paths? or full paths? I like the idea, but need to be careful about portability here... Since these attributes are going to be in an HDF5 file, the path will be in there, and moved around to potentially new machines. Absolute path would break on different machines, but relative path could quickly become out of sync.

The more I think about it, the more I like absolute, then at least you can likely identify the machine from the path.

An alternative (or additional optional attribute) may be to use a unique identifier of the source file on, say, google drive, where applicable.
