### ISSUE TITLE
Include an "range" kwarg for process wigner, tunetest, etc.

### ISSUE THREAD

**Issue by wright-stuff** [wright-group/WrightTools#256]
I think there should be a way for the user to specify that certain colors shouldn't be fit when processing curves. For example, in the attached workup, nothing blue of 565 nm should have any weight in the fitting. While this could someday be done "smartly" I don't think it needs to be.

~Nathan
![000](https://user-images.githubusercontent.com/21300521/30296544-23ec621c-970a-11e7-9084-5afd63bf1877.png)

**Comment by untzag** [comment]
@neffmallon @ksunden https://github.com/wright-group/PyCMDS/issues/136

**Comment by ksunden** [comment]
I feel like this is is already to some degree handled by the global cutoff factor, which there are extant plans (Can't remember which issue, didn't dig far right now) to standardize, and perhaps optimize. 

The ability to remap may help/allow for data to be collected only in ranges with appropriate signal, but once collected, the workup scripts should be able to reject slices with relative ease. The ideas already exist in the package, but may need to have the defaults looked at/ensure that these particular workup methods (And all similar) expose those options to the users.  

I notice here that none of the squares are grayed out as though they are set to NaN. I feel like some of them should be.

I don't particularly like the idea of specifying the range, as that way of manipulating can be done at the data object level, rather than the function call. I prefer methods which look at the values and assess on a relative basis which should be included, allowing slices to be NaN, even large chunks at the edges.

**Comment by neffmallon** [comment]
It looks like this is an issue with the current version of wt on the ps system. Both spectral delay correction methods use the file path, not a data object so you can't edit the data object to get the range you want. Looks like the current code has this fixed. I agree that the data object should be the thing manipulated. I'm closing this issue.
