### ISSUE TITLE
Easy slicing communication with artist for sideplots

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#28]
It would be nice to have sideplot functionality akin to what happens in this figure:
![useful sideplots](https://cloud.githubusercontent.com/assets/11864045/9264245/aa6d2c0e-41e9-11e5-87a1-00027b09834e.png)
So when a sideplot can recognize that it's using a slice from the main dataset, it can visually where the sideplot data is from on the 2D image.  

Specifically looking for functionality of sideplots with 1D data with a "master" 2d data object, but perhaps it's best to abstract this idea to higher dimensions e.g. for connecting different 2D slices of a 3D space as well (and further).

**Comment by untzag** [comment]
Let's say you have a main data object `data` and also an absorbance scan loaded as a data object `abs_data`.

```
artist = wt.artists.mpl_2D(data)
artist.sideplot(abs_data)  # will only try to plot along like axes
artist.sideplot('bin')
points = [6400, 6600, 7500, 8500]
artist.sideplot(points, units='wn')
artist.plot()
```

We would remove `xbin` and `ybin` as arguments of `mpl_2D.plot`. I would want unit handling to be as smart as possible so point would be kept along with units.

Each call to `sideplot` would have kwargs `x` and `y` that are both true by default, but can of course be toggled for fine control.

Binning and slicing would only be done inside `plot` since the relevant array may be changed by arguments like `normalize_slices`.

All of this seems simple and perhaps even elegant to me. The one thing that stumps me at the moment is how to handle choosing colors in the sideplots. Should we have hardwired choices for absorbance and bin (I would propose black and dark blue)? Should we have color be an argument? Maybe the user can supply a colormap alongside of points?

I worry that this may get confusing in conjunction with my light-grey corresponding-dimension lines.

**Comment by ksunden** [comment]
Is this still desired?

**Comment by ddkohler** [comment]
I think this functionality overlaps enough with the cross-hairs of interact2D that we can close this.
