### ISSUE TITLE
collection.keys returns data objects

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#350]
should return names, but get objects

**Comment by ksunden** [comment]
This is happening because we overwrote the `__next__` method.

In the underlying h5py, __next__ is inherited from far upstream, and provides the keys, which can then be used to get the items

one way to fix it would be to make `__next__` return the key rather than the objects themselves

Another way to fix would be to override Keys, note however that doing so would likely mean making it a list, rather than a KeysView, which updates if the object updates
