### ISSUE TITLE
Move fitting helper method to kit?

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#557]
I use the method `wt.fit.leastsqfitter()` quite often when doing very simple fitting tasks. The `fit` module has been removed/hidden in `3.0.0`. Is it allowable to move [this function](https://github.com/wright-group/WrightTools/blob/2.X_backports/WrightTools/fit.py#L61) to `kit`? Maybe we can have a `_fit.py` file in the `kit` folder.

I am of course happy to make a PR once we decide how to handle this issue.

**Comment by untzag** [comment]
you can still access the function, you know---just use from syntax

are you using this function in the context of a publication? if so, I would want to make sure that it is properly a part of WrightTools. otherwise I vote that we just access it manually.

long term I imagine the syntax would be `wt.fit.helpers.leastsqfitter()`

all this said WrightTools belongs to @ksunden now so if you can convince him that this function should go in kit I cannot stop you

**Comment by darienmorrow** [comment]
@untzag I didn't realize I could use something like `from WrightTools import fit as wt_fit` to get it. Thanks for the heads up! 

I think I am fine accessing it manually for now. I do think it falls within the "philosophy" of `kit`, though. I see `leastsqfitter()` in a similar box as `kit.fft`.

**Comment by ksunden** [comment]
For now, I'd say to use `from`

This is, however, a conversation to return to for 3.1.0, which I'd like to start pushing towards soon. (Starting with the data object dependencies, that is `split` etc.)

**Comment by untzag** [comment]
honestly you're probably right @darienmorrow---it should move to kit long term
