### ISSUE TITLE
multiprocess pytest

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#611]
implement multiprocessing in our tests

**Comment by ksunden** [comment]
I've tried out three different plugins which purport to accomplish this task, or something similar:

- [ansible/pytest-mp](github.com/ansible/pytest-mp) : Minimalist implementation that worked perfectly locally, but had an internal error when running on Travis. A bug has been filed with them (ansible/pytest-mp#8). This is a young project, that may not yet be ready for prime time, but worked really well when running on my own machine. They have a README that gives a good overview of key features, but little else to speak of in terms of documentation. Stalled out on Appveyor, may have to disable/selectively enable on *nix because multiprocessing on windows is a mess.

- [reverbc/pytest-concurrent](https://github.com/reverbc/pytest-concurrent) : Not well documented at all, some claims that seem relevant in the README, but I couldn't easily figure them out without looking at their own tests. When I ran it locally, it pegged my CPU at 100% but didn't seem to give any speed improvement. It may be designed to _all_ tests in parallel to get a larger sample size, but that is unclear. By default it spawned an unreasonable number of processes (seemed to be one per test, but it was really unclear). Even when I specified a number, more processes showed up than I expected.

- [pytest-dev/pytest-xdist](github.com/pytest-dev/pytest-xdist) much more broad reaching plugin, allowing things like remote hosts for parallel execution. Had an "INTERNAL ERROR" when running locally using `setup.py test`, stalled out similar to pytest-concurrent when run using `pytest` directly. May be worth further investigation, but runaway processes is concerning. It is better about cancelling with Ctrl-C, though.
