### ISSUE TITLE
wt-convert entry point

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#653]
`wt-convert <values> <current-units> <destinantion-units>`

`<destination-units> optional`

multiple values allowed

returned value printed with either:

- same number of sig-figs
- as integer

(whichever gives more sig figs)

if more than 1 million, use engineering notation

examples of desired behavior follow

simplest case:
```
$ wt-convert 1500 nm wn
6666
```

multiple arguments:
```
$ wt-convert 1300 1500 1600 nm wn
1300 nm is 7692 wn
1500 nm is 6667 wn
1600 nm is 6250 wn
```

no `<destination-units>` provided:
```
$ wt-convert 1500 nm
6666 wn
0.83 eV
826 meV
1.9e14 Hz
199 THz
199861 GHz
```

multiple arguments and no `<destination-units>` provided:
```
$ wt-convert 1300 1500 1600 nm
1300 nm is
  7692 wn
  0.95 eV
  954 meV
  2.3e14 Hz
  231 THz
  230610 GHz
1500 nm is
  6667 wn
  0.83 eV
  826 meV
  1.9e14 Hz
  199 THz
  199861 GHz
1600 nm is
  6250 wn
  0.78 eV
  775 meV
  1.9e14 Hz
  187 THz
  187370 GHz
```

**Comment by ksunden** [comment]
To clarify, This becomes a little tricky to write argparse arguments for, so my suggestion is to forgo trying to create separate arguments, and do the parsing a bit more manually.
We can still use argparse in order to have an easy `--help` where we can describe the arguments, however.

Parsing algorithm should allow listing multiple numbers in a row followed by their unit.
Additional sets of numbers with a given input unit are acceptable:
e.g. `wt-convert 1500 1600 wn 10000 nm eV` should convert three numbers, the first two with wn as the input unit, the last with nm, all outputs in this example are in eV.

If the last two positional arguments are units (i.e. `if wt.units.kind(<arg>):` evaluates to true), the last argument is taken as the desired unit. Otherwise the all valid conversions are to be printed for each input number. (Such conversions can be found with the helper method `get_valid_conversions(<unit>)`)

The remaining args should only consist of numbers and units. The closest unit following each number is the unit for that number. It need not be immediately after the number.
Unrecognized strings which are not numbers or units should cause an error message to be printed to `sys.stdout` and a non-zero exit code (I am personally unopinionated about whether anything gets printed to stdout in this case, @untzag, any opinions?)

**Comment by ksunden** [comment]
Additional flags, such as `--quiet/-q` (unsure of name) could be available to suppress formatting of output to simple numbers (no unit attached). This is default for a single number conversion, and only valid at all if a unit is given to convert to.

One idea which would be nice, but introduces several challenges:
Table view for the conversions to multiple units (may become default if it works perfectly)
`--table/-t` (boolean)
Prints an ASCII (or unicode) table with the input numbers across the top, and their converted values under a separator line (`--------------`).
Gotchas involved:
- Should print the same units on given lines, even if the given units were different. (This may mean leaving blank space or just printing the given number in a cell of the table)
- Ideally if all given numbers ARE in the same unit, no row in the body of the table is present.
- Should limit the width of the table to the terminal width (or 80 chars if we want to be lazy about it)
- If the output would be longer than that, it should break it up into two tables, separated by a blank line

There are some libraries such as [prettytable](https://pypi.org/project/PrettyTable/), a slightly newer fork [PTable](https://pypi.org/project/PTable/), and my favorite from cursory looking [tabulate](https://pypi.org/project/tabulate/)
One of these can help with the formatting of the table, perhaps, Though I do not think any of them handle splitting of wide tables.

**Comment by ksunden** [comment]
@parkertomf Are the desired behaviors outlined here clear to you?
Please let us know if there are any things we can be more clear about

**Comment by ksunden** [comment]
Table view is non-blocking for merge, though I would like quiet mode if we can
