### ISSUE TITLE
Kit leastsq should not except BaseException

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#681]
https://github.com/wright-group/WrightTools/blob/f22920579f45632b4123661d9832ff0cc1b614c4/WrightTools/kit/_leastsq.py#L74

The exception caught should be limited to those known to be raised inside.

**Comment by ksunden** [comment]
@untzag @darienmorrow Dow we know what exception this _should_ be catching?

**Comment by ksunden** [comment]
(or exceptions)

**Comment by darienmorrow** [comment]
I have no idea. I think the idea is to handle any wonky values in the covariance matrix (e.g. inf, -inf), but I don't have good reason to think those would pop up. I will note that the original idea/code come from [this stackoverflow thread](https://stackoverflow.com/questions/14581358/getting-standard-errors-on-fitted-parameters-using-the-optimize-leastsq-method-i/21844726#21844726). 

I think it should be probably just be a `try` `except` instead of using `BaseException`.

**Comment by ksunden** [comment]
Note that just try/except is functionally identical to try/except BaseException. Ideally we know what exceptions may arise from the try block, and only handle those
