### ISSUE TITLE
consider dropping appveyor

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#757]
https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by ksunden** [comment]
Another option is Azure DevOps, Numpy as added them
Spreading out a bit can be nice because sometimes they limit concurrent runs, so having different services will finish faster than having them all the same.

It is true that it is more difficult to maintain the config files, but that cost is relatively minimal, all things considered.

Current leaning: Appveyor is not a bottleneck (though we do only test one python version to ensure that), so "if it ain't broke, don't fix it", but open to discussion

**Comment by untzag** [comment]
not a big enough deal to maintain the issue
