### ISSUE TITLE
[meta] Should we close documentation issues independent of merging to master

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#91]
I move that until the initial documentation work is merged into master, we should close the issues specifically about documentation manually

Once the initial work is to master, the 'fixed in development' label will do just fine, and we would resume holding off on closing issues until the commit is merged to master.

While documentation is our focus, it becomes cluttered to see all of these issues, many of which are actually done in the issue tracker (especially as much of the work is not  yet in development, and thus the label is not applicable)

Alternatively, we could create a 'Documentation completed' label to mark these issues. This label could then be deleted after the initial documentation drive

**Comment by untzag** [comment]
I agree that many of the current issues can be closed. I feel that many of them are not very good atomic issues to begin with. It's hard to break up the documentation issues right now because we are in the middle of changing everything.

I will now close the issues that I think should be closed---they can be reopened if we regret this decision.
